name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - Bootstrap script
        - Installation process
        - Dotfiles configuration
        - Package management
        - Platform support
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Describe alternative approaches

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or examples
      placeholder: Add any other context here

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to work on this feature
          required: false
