# Managed by setup-config.
banner themes/black-pink/banner.png
banner_scale fillscreen
selection_big themes/black-pink/selection_big.png
selection_small themes/black-pink/selection_small.png
hideui hints,label,singleuser,arrows,badges
showtools reboot,shutdown,firmware
use_graphics_for linux,windows
